language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"

addons:
  code_climate:
    repo_token: 36e39f9da06f0fec64d3bf872eb690276b1ab1d4ed32050273209e2da96ec5a3

before_install:
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
  - npm install -g grunt-cli

install:
  - npm install
  - bower install
  - grunt

after_script:
  - npm run coverage
  - cat coverage/lcov.info | codeclimate
